with-expecter: true
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceNameSnake}}.go"
dir: "{{.InterfaceDir}}/mocks"
packages:
  beerdosan-backend/internal/app/repositories:
    interfaces:
      UserRepository:
      SessionRepository:
      LoginAttemptRepository:
  beerdosan-backend/internal/app/service:
    interfaces:
      AuthService:
      JWTService:
      PasswordService:
  beerdosan-backend/internal/pkg/database:
    interfaces:
      TransactionManagerInterface:
  beerdosan-backend/internal/pkg/jwt:
    interfaces:
      JWTService:
  beerdosan-backend/internal/pkg/password:
    interfaces:
      PasswordService:
